### PR TITLE
Model ood pattern

### PR DESCRIPTION
**Pull request by alszla**
Changes:
Enums added for sensor statuses.
Factory method implemented for sensors
FilterSensor was added.
Sensor class changed to interface

To do: Implement Director/Builder OOD pattern.

### CODE REVIEW

**Comment by JosueRodriguezGarcia** [comment]
We have conflicts.

**Comment by JosueRodriguezGarcia** [comment]
ok

**Comment by LimbertVargas** [comment]
ok dude, I review your progress and it's all ok

**Comment by alszla** [comment]
Really...?

**Comment by MadayAlcala** [comment]
I reviewed the code, it's ok. Good job.

**Pull request merged**
